### ISSUE TITLE
ObjectGeoreferencedEvent causes an error when fired for a referenceable dexterity type

### ISSUE THREAD

**Issue by href** [collective/collective.geo.geographer#5]
Using collective.geo.behaviour and 'Referencable' on a dexterity type I get the following error:

    Traceback (innermost last):
    Module ZPublisher.Publish, line 126, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 46, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.dexterity.browser.add, line 112, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 141, in update
    Module plone.app.z3cform.csrf, line 21, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module plone.dexterity.browser.add, line 99, in handleAdd
    Module z3c.form.form, line 245, in createAndAdd
    Module plone.dexterity.browser.add, line 68, in create
    Module z3c.form.form, line 49, in applyChanges
    Module z3c.form.datamanager, line 91, in set
    Module collective.geo.behaviour.behaviour, line 55, in coordinates
    Module collective.geo.geographer.geo, line 55, in setGeoInterface
    Module zope.event, line 31, in notify
    Module zope.component.event, line 24, in dispatch
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module zope.component.event, line 32, in objectEventNotify
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module plone.app.referenceablebehavior.uidcatalog, line 31, in modified_handler
    Module OFS.Traversable, line 118, in getPhysicalPath
    Module OFS.SimpleItem, line 112, in getId
    AttributeError: This object has no id

The problem is that plone.app.referenceablebehavior subscribes to IObjectModifiedEvent from which IObjectGeoreferencedEvent inherits. It then tries to get the physical path which fails without id.

I'm not sure how this should be fixed, I can work around the issue by not using referenceable-behavior when creating the objects, or by adding a check to ensure that the georeferenced-event is only fired if there's an id.

**Comment by keul** [comment]
I reopen this issue because with:
* Plone 4.3.9
* collective.geo.bundle 2.3
* collective.geo.behaviour 1.2
* collective.geo.geographer 2.0
* plone.app.referenceablebehavior 0.7.4

The issue is still there.

It not seems related (only) to the missing of content's id (so for "temporary" objects).

I can cleanly reproduce the issue:
* creating a new TTW dexterity content type
* enabling the "*Referenceable by Archetypes*" and "Collective Geo Maps"

If I create a new content type and immediately provide a geo coordinates I get the traceback already mentioned:

```
2016-05-02 15:55:06 ERROR Zope.SiteErrorLog 1462197306.350.464531501492 http://localhost:8080/Plone/++add++tipo_1
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 118, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 101, in handleAdd
  Module z3c.form.form, line 263, in createAndAdd
  Module plone.dexterity.browser.add, line 68, in create
  Module z3c.form.form, line 51, in applyChanges
  Module z3c.form.datamanager, line 91, in set
  Module collective.geo.behaviour.behaviour, line 52, in coordinates
  Module collective.geo.geographer.geo, line 55, in setGeoInterface
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.referenceablebehavior.uidcatalog, line 39, in modified_handler
  Module OFS.Traversable, line 118, in getPhysicalPath
  Module OFS.SimpleItem, line 112, in getId
AttributeError: This object has no id
```

If I don't provide geo data I can save my content, but also adding the coordinates later gives me an error:

```
2016-05-02 15:57:45 ERROR Zope.SiteErrorLog 1462197465.420.53232791832 http://localhost:8080/Plone/test-tipo-1/@@edit
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.edit, line 64, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.edit, line 28, in handleApply
  Module z3c.form.group, line 116, in applyChanges
  Module z3c.form.group, line 82, in applyChanges
  Module z3c.form.form, line 51, in applyChanges
  Module z3c.form.datamanager, line 91, in set
  Module collective.geo.behaviour.behaviour, line 52, in coordinates
  Module collective.geo.geographer.geo, line 55, in setGeoInterface
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.referenceablebehavior.uidcatalog, line 43, in modified_handler
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.app.referenceablebehavior.referenceable, line 52, in __init__
  Module Products.CMFCore.utils, line 10, in check_getToolByName
  Module Products.CMFCore.utils, line 120, in getToolByName
AttributeError: reference_catalog
```

The issue disappear as soon as I don't enable both of the behaviors.
